disabled_rules: # rule identifiers to exclude from running
- line_length
- trailing_whitespace
- todo
- function_body_length

identifier_name:
min_length: 2
excluded: # excluded via string array
- id
- x
- y
- xy
- t

type_name:
min_length: 2

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods

